document.write('<div class="gameChoice showBox">'
+'<div class="triangle-up">'
   +'<div class="outerTri fl">'
   +'</div>'
   +'<div class="innerTri fl">'
   +'</div>'
   +'<div class="cl"></div>'
   +'</div>'
   +'<div class="topBox">'
   +'<ul>'
   +'<li class="active">网络游戏</li>'
   +'<li>苹果手游</li>'
   +'<li>安卓手游</li>'
   +'</ul>'
   +'</div>'
   +'<div class="letterBox">'
   +'<span class="fl">热门游戏</span>'
   +'<ul class="fl">'
   +'<li><a href="#">A</a></li>'
   +'<li><a href="#">B</a></li>'
   +'<li><a href="#">C</a></li>'
   +'<li><a href="#">D</a></li>'
   +'<li><a href="#">E</a></li>'
   +'<li><a href="#">F</a></li>'
   +'<li><a href="#">G</a></li>'
   +'<li><a href="#">H</a></li>'
   +'<li><a href="#">I</a></li>'
   +'<li><a href="#">J</a></li>'
   +'<li><a href="#">K</a></li>'
   +'<li><a href="#">L</a></li>'
   +'<li><a href="#">M</a></li>'
   +'<li><a href="#">N</a></li>'
   +'<li><a href="#">O</a></li>'
   +'<li><a href="#">P</a></li>'
   +'<li><a href="#">Q</a></li>'
   +'<li><a href="#">R</a></li>'
   +'<li><a href="#">S</a></li>'
   +'<li><a href="#">T</a></li>'
   +'<li><a href="#">U</a></li>'
   +'<li><a href="#">V</a></li>'
   +'<li><a href="#">W</a></li>'
   +'<li><a href="#">X</a></li>'
   +'<li><a href="#">Y</a></li>'
   +'<li><a href="#">Z</a></li>'
   +'</ul>'
   +'<div class="cl"></div>'
   +'</div>'
   +'<div class="choiceMainBox">'
   +'<ul>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'<li>地下城与勇士</li>'
   +'</ul>'
   +'</div>'
   +'</div>'
   +'<div class="areaChoice showBox">'
   +'<div class="triangle-up">'
   +'<div class="outerTri fl">'
   +'</div>'
   +'<div class="innerTri fl">'
   +'</div>'
   +'<div class="cl"></div>'
   +'</div>'
   +'<div class="topBox">'
   +'<h1>请选择区</h1>'
   +'</div>'
   +'<div class="choiceMainBox">'
   +'<ul>'
   +'<li>广东1区</li>'
   +'<li>广东2区</li>'
   +'<li>广东3区</li>'
   +'<li>广东4区</li>'
   +'<li>广东5区</li>'
   +'<li>广东6区</li>'
   +'<li>广东7区</li>'
   +'<li>广东8区</li>'
   +'<li>广东9区</li>'
   +'<li>广东10区</li>'
   +'<li>广东11区</li>'
   +'<li>广东12区</li>'
   +'<li>广东13区</li>'
   +'</ul>'
   +'</div>'
   +'</div>'
   +'<div class="serverChoice showBox">'
   +'<div class="triangle-up">'
   +'<div class="outerTri fl">'
   +'</div>'
   +'<div class="innerTri fl">'
   +'</div>'
   +'<div class="cl"></div>'
   +'</div>'
   +'<div class="topBox">'
   +'<h1>请选择服</h1>'
   +'</div>'
   +'<div class="choiceMainBox">'
   +'<ul>'
   +'<li>广东1区</li>'
   +'<li>广东2区</li>'
   +'<li>广东3区</li>'
   +'<li>广东4区</li>'
   +'<li>广东5区</li>'
   +'<li>广东6区</li>'
   +'<li>广东7区</li>'
   +'<li>广东8区</li>'
   +'<li>广东9区</li>'
   +'<li>广东10区</li>'
   +'<li>广东11区</li>'
   +'<li>广东12区</li>'
   +'<li>广东13区</li>'
   +'</ul>'
   +'</div>'
   +'</div>'
   +'<div class="goodsChoice showBox">'
   +'<div class="triangle-up">'
   +'<div class="outerTri fl">'
   +'</div>'
   +'<div class="innerTri fl">'
   +'</div>'
   +'<div class="cl"></div>'
   +'</div>'
   +'<div class="topBox">'
   +'<h1>请选择商品分类</h1>'
   +'</div>'
   +'<div class="choiceMainBox">'
   +'<ul>'
   +'<li>游戏币</li>'
   +'<li>装备</li>'
   +'<li>游戏账号</li>'
   +'<li>游戏代练</li>'
   +'<li>点卡</li>'
   +'<li>材料</li>'
   +'<li>点券</li>'
   +'<li>激活码</li>'
   +'<li>QB</li>'
   +'<li>材料</li>'
   +'<li>点券</li>'
   +'<li>激活码</li>'
   +'<li>材料</li>'
   +'<li>点券</li>'
   +'<li>激活码</li>'
   +'</ul>'
   +'</div>'
   +'</div>'
   +'<script src="../js/searchAction.js"></script>')